spring:
  main:
    web-application-type: none
  task:
    execution:
      pool:
        core-size: 2
        keep-alive: 1s

trafiklab:
  base-url: https://api.sl.se/api2/LineData.json
  api-key: ${TRAFIKLAB_API_KEY}

logging:
  level:
    root: info
    se.perloven: debug
