spring:
  main:
    web-application-type: none
  jackson:
    mapper:
      accept-case-insensitive-properties: true

trafiklab:
  base-url: https://api.sl.se/api2/LineData.json
  api-key: ${TRAFIKLAB_API_KEY}

logging:
  level:
    root: info
    se.perloven: debug
